### ISSUE TITLE
Blink Alpha 3 checklist

### ISSUE THREAD

**Issue by prayag17** [prayag17/JellyPlayer#338]
> [!Important]
> JellyPlayer will be renamed to Blink by Alpha 3

This issue contains every major changes slated for Blink Alpha 3
- [ ] Fix the `error reading undefined of SOMETHING` errors which plague the entire app
- [ ] Improve video and audio playback experience
- [ ] Jellyfin 10.9 feature support #337
- [ ] Styling and UI improvments
- [ ] Move the entire codebase to TypeScript
- [ ] Improve Login and application setup process
- [ ] Move from `react-router-dom` to `tanstack-router` #334 
- [ ] Improve library browsing experience 
- [ ] Photos support
- [ ] Books support
- [ ] Discord RPC support
- [ ] [Intro Skipper](https://github.com/jumoog/intro-skipper) support
- [x] Queue playback support
- [x] Add application updater

Also to clarify the release versions...
- Stable version will have `vX.X.X` version number
- Beta release will have `vX.X.X-betaY` version number and generally this version will have all the features planned for the next release
- Alpha release will have `v1.0.0-alphaY` version number. Alpha versioning will be dropped for future build coming after v1
- Dev version contains all the experimental feature that may or may not make it into the stable release and will follow `v0.0.X-dev`. Dev verisoning will also be dropped after v1.
